### ISSUE TITLE
Build error "The 'run' command is only supported from within a workspace (below a directory having a WORKSPACE file)" - Mac M1/Sonoma

### ISSUE THREAD

**Issue by wolframteetz** [google/temporian#292]
(...)
  Building wheels for collected packages: temporian
  Building wheel for temporian (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for temporian (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [60 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      A setup.py file already exists. Using it.
      running build
      running bazel_build
      WARNING: Invoking Bazel in batch mode since it is not invoked from within a workspace (below a directory having a WORKSPACE file).
      **ERROR: The 'run' command is only supported from within a workspace (below a directory having a WORKSPACE file).**
      See documentation at https://bazel.build/concepts/build-ref#workspace
      Traceback (most recent call last):
        File "/private/var/folders/n1/dwc4fjhs62xbt_std9ymr3bc0000gn/T/pip-install-bmh2m7yg/temporian_bf6813aa05ee4ca6805a0cd8cb95db2a/setup.py", line 80, in <module>
          setup(**setup_kwargs)
        File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)

**Comment by wolframteetz** [comment]
If I "sudo touch /private/WORKSPACE", it gives

Building wheels for collected packages: temporian
  Building wheel for temporian (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for temporian (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      A setup.py file already exists. Using it.
      running build
      running bazel_build
      Starting local Bazel server and connecting to it...
      Loading:
      Loading:
      Loading: 0 packages loaded
      ERROR: Skipping '@temporian//config:move_generated_files': no such package '@temporian//config': The repository '@temporian' could not be resolved: Repository '@temporian' is not defined
      WARNING: Target pattern parsing failed.
      ERROR: no such package '@temporian//config': The repository '@temporian' could not be resolved: Repository '@temporian' is not defined
      INFO: Elapsed time: 1.455s

**Comment by wolframteetz** [comment]
I can and have built from source which works fine just as described in CONTRIBUTING.md

**Comment by rstz** [comment]
Hi, thank you for reporting this. We're looking into improving the build process and make it work with pip directly. Also note that we will upload the missing MacOS Arm64 wheels to Pypi very shorty.

**Comment by soerenml** [comment]
Thank you very much for looking into this. I am still having the same issue.

**Comment by ianspektor** [comment]
Hey @soerenml!

What are you running to install Temporian, and in what Mac model and MacOS/Python versions? Wheels for version 0.7.0 (latest) for Mac ARM are up on PyPI, so pip should be able to pull those instead of trying to build.
